### ISSUE TITLE
Runtime-related Issue

### ISSUE THREAD

**Issue by Le1223** [YanqiangLi/NanoNm#2]
Hello,
I am encountering the following error when running the script extract_raw_and_feature_fast_AUCG.py. I have tried running the command multiple times with different threading configurations, but the error persists. The command I am using is:
'
python extract_raw_and_feature_fast_AUCG.py --cpu=1 --fl=guppy.list -o guppy.feature --clip=5
'
Here is the error message I am getting:
![image](https://github.com/user-attachments/assets/48dfce57-122c-46ee-bbbf-e5d5e3f2a285)

**Comment by YanqiangLi** [comment]
Hello Le1223, it looks like the error message raised from the tombo, could you please check whether it is works correctly.

Best.

From: Le1223 ***@***.***>
Date: Monday, September 23, 2024 at 01:31
To: YanqiangLi/NanoNm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YanqiangLi/NanoNm] Runtime-related Issue (Issue #2)

Hello,
I am encountering the following error when running the script extract_raw_and_feature_fast_AUCG.py. I have tried running the command multiple times with different threading configurations, but the error persists. The command I am using is:
'
python extract_raw_and_feature_fast_AUCG.py --cpu=1 --fl=guppy.list -o guppy.feature --clip=5
'
Here is the error message I am getting:
image.png (view on web)<https://github.com/user-attachments/assets/48dfce57-122c-46ee-bbbf-e5d5e3f2a285>

**Comment by Le1223** [comment]
I don't know if it's a data problem. I used another data and he was able to run the entire process

**Comment by YanqiangLi** [comment]
Great news!

**Comment by YanqiangLi** [comment]
solved
