### ISSUE TITLE
questions about detect the Nm of mRNA by NanoNm if can use .bam data

### ISSUE THREAD

**Issue by violet-everygarden** [YanqiangLi/NanoNm#3]
Hello, we tried to use the NanoNm to detect the Nm site of directRNA-seq data, but the server can't run such a large amount of data. I would like to ask whether it is possible to use .bam data for Nm prediction? If so, how should the code be changed?

**Comment by YanqiangLi** [comment]
Hello there, I do not think the only .bam data is a valid input for NanoNm. I suggest you can extract the features for each fast5 folder, merge all of these features together and combine with bam file to do the final prediction.

**Comment by violet-everygarden** [comment]
Thank you for your prompt reply and help. I will try your suggestion.
